services:
  postgres:
    image: postgres:17
    container_name: cpp-auth-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: auth_service
      POSTGRES_PASSWORD: auth_service

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service -d auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: